steps:
- id: "Teste Unitário"
  name: 'gcr.io/cloud-builders/go'
  args: ['test', './src']
  env: ['GOPATH=.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/img-go-soma:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/img-go-soma:latest']

images: 
- 'gcr.io/$PROJECT_ID/img-go-soma:latest'